/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'id' : bigint,
  'model' : string,
  'licensePlate' : string,
  'owner' : Principal,
  'make' : string,
}
export interface WashAppointment {
  'id' : bigint,
  'status' : AppointmentStatus,
  'scheduledDate' : string,
  'owner' : Principal,
  'scheduledTime' : string,
  'createdAt' : bigint,
  'washType' : WashType,
  'address' : string,
  'vehicleId' : bigint,
}
export interface WashStats {
  'completedWashes' : bigint,
  'upcomingWashes' : bigint,
  'cancelledWashes' : bigint,
  'totalWashes' : bigint,
}
export type WashType = { 'premium' : null } |
  { 'basic' : null } |
  { 'standard' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVehicle' : ActorMethod<[string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookWash' : ActorMethod<[bigint, WashType, string, string, string], bigint>,
  'cancelAppointment' : ActorMethod<[bigint], undefined>,
  'deleteVehicle' : ActorMethod<[bigint], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<WashAppointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAppointments' : ActorMethod<[], Array<WashAppointment>>,
  'getMyPastAppointments' : ActorMethod<[], Array<WashAppointment>>,
  'getMyUpcomingAppointments' : ActorMethod<[], Array<WashAppointment>>,
  'getMyWashStats' : ActorMethod<[], WashStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyVehicles' : ActorMethod<[], Array<Vehicle>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAppointmentStatus' : ActorMethod<
    [bigint, AppointmentStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];