/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WashType = IDL.Variant({
  'premium' : IDL.Null,
  'basic' : IDL.Null,
  'standard' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const WashAppointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : AppointmentStatus,
  'scheduledDate' : IDL.Text,
  'owner' : IDL.Principal,
  'scheduledTime' : IDL.Text,
  'createdAt' : IDL.Int,
  'washType' : WashType,
  'address' : IDL.Text,
  'vehicleId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const WashStats = IDL.Record({
  'completedWashes' : IDL.Nat,
  'upcomingWashes' : IDL.Nat,
  'cancelledWashes' : IDL.Nat,
  'totalWashes' : IDL.Nat,
});
export const Vehicle = IDL.Record({
  'id' : IDL.Nat,
  'model' : IDL.Text,
  'licensePlate' : IDL.Text,
  'owner' : IDL.Principal,
  'make' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addVehicle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookWash' : IDL.Func(
      [IDL.Nat, WashType, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'cancelAppointment' : IDL.Func([IDL.Nat], [], []),
  'deleteVehicle' : IDL.Func([IDL.Nat], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(WashAppointment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAppointments' : IDL.Func([], [IDL.Vec(WashAppointment)], ['query']),
  'getMyPastAppointments' : IDL.Func([], [IDL.Vec(WashAppointment)], ['query']),
  'getMyUpcomingAppointments' : IDL.Func(
      [],
      [IDL.Vec(WashAppointment)],
      ['query'],
    ),
  'getMyWashStats' : IDL.Func([], [WashStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WashType = IDL.Variant({
    'premium' : IDL.Null,
    'basic' : IDL.Null,
    'standard' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const WashAppointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : AppointmentStatus,
    'scheduledDate' : IDL.Text,
    'owner' : IDL.Principal,
    'scheduledTime' : IDL.Text,
    'createdAt' : IDL.Int,
    'washType' : WashType,
    'address' : IDL.Text,
    'vehicleId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const WashStats = IDL.Record({
    'completedWashes' : IDL.Nat,
    'upcomingWashes' : IDL.Nat,
    'cancelledWashes' : IDL.Nat,
    'totalWashes' : IDL.Nat,
  });
  const Vehicle = IDL.Record({
    'id' : IDL.Nat,
    'model' : IDL.Text,
    'licensePlate' : IDL.Text,
    'owner' : IDL.Principal,
    'make' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addVehicle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookWash' : IDL.Func(
        [IDL.Nat, WashType, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'cancelAppointment' : IDL.Func([IDL.Nat], [], []),
    'deleteVehicle' : IDL.Func([IDL.Nat], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(WashAppointment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAppointments' : IDL.Func([], [IDL.Vec(WashAppointment)], ['query']),
    'getMyPastAppointments' : IDL.Func(
        [],
        [IDL.Vec(WashAppointment)],
        ['query'],
      ),
    'getMyUpcomingAppointments' : IDL.Func(
        [],
        [IDL.Vec(WashAppointment)],
        ['query'],
      ),
    'getMyWashStats' : IDL.Func([], [WashStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };